server.port: 8080

# JPA Hibernate
spring.jpa:
  database: H2
  properties.hibernate.hbm2ddl.auto: create
  properties.hibernate.format_sql: true
  properties.hibernate.use_sql_comments: true
  properties.hibernate.show_sql: true
  properties.hibernate.id.new_generator_mappings: true

# DataSource
spring.datasource:
  url: jdbc:h2:tcp://localhost/~/test;MVCC=TRUE
  driverClassName: org.h2.Driver
  username: sa
  password:
  initialize: true